enum GraphResponseStatuses {
	BAD_ID = 'BAD_ID',
	ERROR = 'ERROR',
	NOT_IN_DB = 'NOT_IN_DB',
	OLD_GRAPH = 'OLD_GRAPH',
	FRESH_GRAPH = 'FRESH_GRAPH',
	IN_PROGRESS = 'IN_PROGRESS',
	QUEUED = 'QUEUED',
	BAD_TOKEN = 'BAD_TOKEN',
	BAD_REQUEST = 'BAD_REQUEST',
	OUT_OF_REQUESTS = 'OUT_OF_REQUESTS',
}

